### ISSUE TITLE
Problems with base64 strings

### ISSUE THREAD

**Issue by avocadowastaken** [nojvek/urltron#6]
#### Example:
```js
require('urltron').parse('a=n&b=e2hleTogInlhISIsICJvaCI6ICJvaCEifQ==');
```
#### Throws:
```node
Uncaught Error: urltron.parse: expecting:'&', found:'='
    at _ensureToken (/node_modules/urltron/dist/index.js:93:15)
    at _parseObject (/node_modules/urltron/dist/index.js:120:13)
    at _parseValue (/node_modules/urltron/dist/index.js:155:16)
    at Object.parse (/node_modules/urltron/dist/index.js:195:12)
```

#### Context:

I've found this error was thrown in Sentry, something is injecting unencoded base64 param (`notification_link_uid`) into location search, and this led to crash.

#### Workaround:

```js
require('urltron').parse(new URLSearchParams(search).toString());
```

**Comment by nojvek** [comment]
Hey @umidbekk, 

If something external is messing the url format, then urltron would not be able to process it. urltron expects the values to be url encoded so this needs to be.

`a=n&b=e2hleTogInlhISIsICJvaCI6ICJvaCEifQ%3D%3D`

I would suggest you manually filter out the keys you don't control before passin to urltron.

**Comment by avocadowastaken** [comment]
@nojvek thanks for the response. I will keep my workaround as a permanent then with the link to your comment.

Could you please add a note about that in the readme?

We're start using `urltron` as  drop-in replacement for the `URLSearchParams` in big project, and everything went well, but some rare edge cases like that keep crashing the app, and it would be helpful to know about that limitation beforehand.

**Comment by nojvek** [comment]
Absolutely can do. Thanks for reporting this.

**Comment by nojvek** [comment]
I would love a list of companies using urltron on the README.md. Would you be open to having your company's name on README.md ?

**Comment by nojvek** [comment]
@umidbekk see https://github.com/recurrency/urltron/blob/main/README.md#caveats

**Comment by avocadowastaken** [comment]
> I would love a list of companies using urltron on the README.md. Would you be open to having your company's name on README.md ?

@nojvek Yeah, sure, why not! You can add @superdispatch to the list.
